version: '3'
services:
  web:
    build:
      context: .
      args:
        - ENV=dev
    ports:
     - "8000:80"
    volumes:
     - .:/go/src/app
    environment:
      - GROUP_IDS
      - MEETUP_KEY
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=localmeetups
      - MYSQL_HOST=local-meetups-api-db
      - PUBSUB_USER=guest
      - PUBSUB_PASSWORD=guest
    entrypoint: fresh
    links:
      - db:local-meetups-api-db
      - messaging:local-meetups-api-mssaging
    depends_on:
      - db
      - messaging
  db:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=localmeetups
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5000:3306"
  messaging:
    image: rabbitmq:3-management
    hostname: messaging
    ports:
      - "15672:15672"
