version: '3'
services:
  web:
    build:
      context: .
      args:
        - ENV=dev
    ports:
     - "8000:80"
    volumes:
     - .:/go/src/app
    environment:
      - GROUP_IDS
      - MEETUP_KEY
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=localmeetups
      - MYSQL_HOST=local-meetups-api-db
      - PUBSUB_USER=admin
      - PUBSUB_PASSWORD=admin
    entrypoint: fresh
    links:
      - db:local-meetups-api-db
      - messaging:local-meetups-api-messaging
    depends_on:
      - db
      - messaging
  db:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=localmeetups
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5000:3306"
  messaging:
    image: webcenter/activemq
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
    ports:
     - "8161:8161"
