version: '3'
services:
  web:
    build:
      context: .
      args:
        - ENV=dev
    ports:
     - "8000:80"
    volumes:
     - .:/go/src/app
    environment:
      - GROUP_IDS
      - MEETUP_KEY
    entrypoint: fresh
    links:
      - db:db
    depends_on:
      - db
  db:
    image: couchdb:2
    ports:
     - "5984:5984"
