version: '3'
services:
  web:
    build:
      context: .
      args:
        - ENV=dev
    ports:
     - "8000:80"
    volumes:
     - .:/go/src/app
    environment:
      - GROUP_IDS
      - MEETUP_KEY
      - COUCHDB_HOST=local-meetups-api-db
      - COUCHDB_PORT=5984
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    entrypoint: fresh
    links:
      - db:local-meetups-api-db
    depends_on:
      - db
  db:
    image: couchdb:2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
     - "5984:5984"
